name: AzoSpawner
author: Azorimor
website: www.github.com/azorimor/mc-azospawner
main: io.github.azorimor.azospawner.AzoSpawner
version: 1.0.1
description: Controlling Spawners
api-version: 1.13
commands:
  givespawner:
    description: Gives the player an amount of specific spawners.
    usage: givespawner <entityType> [amount]
  givepickaxe:
    description: Gives the player the pickaxe tool to break spawners.
    usage: givepickaxe [player]